server: 
  port: 8082

spring:
  application: 
    name: notification
  # reuse exact same datasource configuration for this course, ideally you should have a separate database for each microservice
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/notification
    password: '12345'
  jpa: 
    hibernate:
      # create-drop will drop the schema and recreate it at every start of the application (ddl: data definition language)
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true