spring:
  application: 
    name: eureka-server
server: 
  port: 8761
  wait-time-in-ms-when-sync-empty: 0
eureka:
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/