server: 
  port: 8083
spring: 
  application: 
    name: api-gateway
  zipkin:
    base-url: http://zipkin.default.svc.cluster.local:80/
  cloud: 
    gateway: 
      routes: 
        - id: customer
          uri: lb://CUSTOMER
          predicates: 
            - Path=/api/v1/customers/**
