server: 
  port: 8080

spring:
  application: 
    name: customer
  datasource: 
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    password: '12345'
  jpa:
      hibernate:
          ddl-auto: create
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              format_sql: true
      show-sql: true
eureka:
  client: 
    fetchRegistry: true
    registerWithEureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/