apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: fraud
        image: gcr.io/os-app-deploy/fraud:latest
        args: ["-jar", "/usr/app/fraud-1.0-SNAPSHOT.jar"]
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgres-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: fraud
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: fraud