apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: gcr.io/os-app-deploy/notification:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "200m"  # 200 milliCPU, or 0.2 of a CPU core
            memory: "256Mi"
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgres-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabitmq-rabbitmq
              key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: notification